kind: pipeline
type: kubernetes
name: default

steps:
  - name: install_dependencies
    image: node:12
    commands:
      - npm ci

  - name: lint
    image: node:12
    commands:
      - npm run format:check
    depends_on: [install_dependencies]

  - name: test
    image: node:12
    commands:
      - npm run test
    depends_on: [install_dependencies]

  - name: build
    image: node:12
    commands:
      - npm run build
    depends_on: [install_dependencies]

  - name: Semantical Versionning
    image: python:3.6
    commands:
      - mkdir ~/.ssh
      - echo $CI_SSH_KEY > ~/.ssh/id_rsa
      - pip install -r .semver/requirements.txt
      - python .semver/main.py
    depends_on: [install_dependencies]

  - name: Changelog
    image: ruby:2.6.4-alpine3.9
    commands:
      - apk add -y git
      - mkdir ~/.ssh
      - echo $CI_SSH_KEY > ~/.ssh/id_rsa
      - gem install github_changelog_generator
      - github_changelog_generator -u "Ked57" -p "mspr-user-api" -o CHANGELOG.md --token 7468fe12948b508fabd1441b73ca62b1c51488b0
      - ls -la
      - pwd
      - git status && git add . && git commit -m "Added New Changelog" && git push
    depends_on: [install_dependencies]

    environment:
      CI_REPOSITORY_URL:
        from_secret: CI_REPOSITORY_URL
      CI_SSH_KEY:
        from_secret: CI_SSH_KEY
    depends_on: [install_dependencies]
    